[versions]
spring-boot = "3.3.5"
spring-dependency-management = "1.1.6"
lombok = "8.10.2"
jgit = "7.0.0.202409031743-r"
neo4j = "5.25.1"
mapstruct = "1.6.2"
commons-io = "2.18.0"
neo4j-harness = "5.26.0"
gson = "2.11.0"

[plugins]
mcm-java-conventions = { id = "at.ac.tuwien.model.change.management.java-conventions" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

[libraries]
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
jgit-junit = {module = "org.eclipse.jgit:org.eclipse.jgit.junit", version.ref = "jgit" }
neo4j = { module = "org.neo4j:neo4j", version.ref = "neo4j" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
# NOTE: versions for spring dependencies are managed by the `spring.dependency-management` Gradle plugin
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-data-neo4j = { module = "org.springframework.boot:spring-boot-starter-data-neo4j" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
neo4j-harness = { module = "org.neo4j.test:neo4j-harness", version.ref = "neo4j-harness" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3" }